### ISSUE TITLE
请问关于macvlan网络应该如何正确配置

### ISSUE THREAD

**Issue by seepine** [14790897/OpenWrt-In-Docker#3]
我目前路由器是 `192.168.2.1`，mac是 `192.168.2.10`，nas是`192.168.2.5`
在nas上通过docker compose部署，复制yml修改其中macvlan config部分为192.168.2.x的，是否正确，容器启动后，mac无法通过192.168.2.188访问， 看容器ip是192.168.2.2，但是通过它也无法访问

```yml
services:
  openwrt:
    image: ghcr.nju.edu.cn/14790897/openwrt:x86_64
    container_name: openwrt
    restart: always
    cap_add:
      - NET_ADMIN  # 增加 NET_ADMIN 权限
      - NET_RAW
    networks:
      macvlan_net:
    command: /sbin/init

networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: eno1 # 宿主机的网卡名称，需要使用ip link show 手动查询，保持一致
    ipam:
      config:
        - subnet: 192.168.2.0/24 # 定义容器使用的子网，需要和当前网络一致
          gateway: 192.168.2.1 # 定义网关，需要和当前网络一致
```
